### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by zploskey** [Wonder-Technology/Wonder-bs-puppeteer#1]
Hello,

This fork of [bs-puppeteer](https://github.com/bs-puppeteer/bs-puppeteer/) has removed our LICENSE file. This is a violation of the MIT license which states, "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." I am the primary copyright holder. Please either put the LICENSE file back or remove this repository. This includes the package you have published to NPM.

Furthermore there have been significant improvements to these bindings since you forked. Please consider just using our library as a dependency.

I would also note that there are other repositories under @Wonder-Technology that are similarly in violation of open source licenses. I encourage you to come into compliance with those licenses as well.

I will give you a few days to fix the situation before taking any further action.

**Comment by yyc-git** [comment]
I have add LICENSE, please check it.
thanks for your request

**Comment by zploskey** [comment]
Thanks! And please do check out the activity upstream. We're merging a bunch of big improvements.

**Comment by yyc-git** [comment]
Good job! Thanks for your great job!
